"""Initial migration

Revision ID: a7fbe32cf800
Revises: 
Create Date: 2023-08-19 21:49:21.815568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fbe32cf800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('Price', sa.String(length=20), nullable=True),
    sa.Column('Size', sa.String(length=20), nullable=True),
    sa.Column('Activity', sa.Integer(), nullable=True),
    sa.Column('Hair_length', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breed')
    # ### end Alembic commands ###
